/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package beadandopizza;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RichterBalázsKriszti
 */
public class BeadandoPizza extends javax.swing.JFrame {

    /**
     * Creates new form BeadandoPizza
     */
    public BeadandoPizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlFelso = new javax.swing.JPanel();
        lblMotto = new javax.swing.JLabel();
        lblRendeloifelulet = new javax.swing.JLabel();
        lblPizzaHub = new javax.swing.JLabel();
        pnlPizzaink = new javax.swing.JPanel();
        lblHusimadoMellett = new javax.swing.JLabel();
        lblSongokuMellett = new javax.swing.JLabel();
        lblNegysajtosMellett = new javax.swing.JLabel();
        lblDiavolaMellett = new javax.swing.JLabel();
        txfSongukoMellett = new javax.swing.JTextField();
        txfHusimadoMellett = new javax.swing.JTextField();
        txfNegysajtosMellett = new javax.swing.JTextField();
        txfDiavolaMellett = new javax.swing.JTextField();
        ckbHusimado = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        pnlExtrafeltet = new javax.swing.JPanel();
        rdbHagyma = new javax.swing.JRadioButton();
        rdbPaprika = new javax.swing.JRadioButton();
        rdbJalapeno = new javax.swing.JRadioButton();
        rdbSzalami = new javax.swing.JRadioButton();
        btnBezaras = new javax.swing.JToggleButton();
        btnLeadas = new javax.swing.JToggleButton();
        pnlFizetesimod = new javax.swing.JPanel();
        rdbKp = new javax.swing.JRadioButton();
        rdbUtalas = new javax.swing.JRadioButton();
        rdbBkFiz = new javax.swing.JRadioButton();
        rdbBkUtanvet = new javax.swing.JRadioButton();
        pnlEtlapkepek = new javax.swing.JPanel();
        pnlHusimadoAr = new javax.swing.JPanel();
        lblHusimado = new javax.swing.JLabel();
        pnlSonGokuAr = new javax.swing.JPanel();
        lblSongoku = new javax.swing.JLabel();
        pnlNegysajtosAr = new javax.swing.JPanel();
        lblNegysajtos = new javax.swing.JLabel();
        pnlDiavolaAr = new javax.swing.JPanel();
        lblDiavola = new javax.swing.JLabel();
        pnlAtveletimod = new javax.swing.JPanel();
        cbxAtveteliMod = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlFelso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMotto.setText("Egyen egy finom pizzát, jó áron!");

        lblRendeloifelulet.setText("Rendelői felület");

        lblPizzaHub.setText("Pizza Hub");

        javax.swing.GroupLayout pnlFelsoLayout = new javax.swing.GroupLayout(pnlFelso);
        pnlFelso.setLayout(pnlFelsoLayout);
        pnlFelsoLayout.setHorizontalGroup(
            pnlFelsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFelsoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRendeloifelulet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPizzaHub)
                .addGap(134, 134, 134)
                .addComponent(lblMotto)
                .addContainerGap())
        );
        pnlFelsoLayout.setVerticalGroup(
            pnlFelsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFelsoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFelsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRendeloifelulet)
                    .addComponent(lblPizzaHub)
                    .addComponent(lblMotto))
                .addContainerGap())
        );

        pnlPizzaink.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hagyományos Pizzáink (32 cm)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblHusimadoMellett.setText("db:");

        lblSongokuMellett.setText("db:");

        lblNegysajtosMellett.setText("db:");

        lblDiavolaMellett.setText("db:");

        txfSongukoMellett.setText("Nem kérek");

        txfHusimadoMellett.setText("Nem kérek");

        txfNegysajtosMellett.setText("Nem kérek");

        txfDiavolaMellett.setText("Nem kérek");

        ckbHusimado.setText("Húsimádó");
        ckbHusimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbHusimadoActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Son-Goku");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Négysajtos");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Diavola");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPizzainkLayout = new javax.swing.GroupLayout(pnlPizzaink);
        pnlPizzaink.setLayout(pnlPizzainkLayout);
        pnlPizzainkLayout.setHorizontalGroup(
            pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPizzainkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPizzainkLayout.createSequentialGroup()
                        .addComponent(ckbHusimado)
                        .addGap(12, 12, 12)
                        .addComponent(lblHusimadoMellett)
                        .addGap(4, 4, 4)
                        .addComponent(txfHusimadoMellett, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addGroup(pnlPizzainkLayout.createSequentialGroup()
                        .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3))
                        .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPizzainkLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNegysajtosMellett)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfNegysajtosMellett))
                            .addGroup(pnlPizzainkLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblDiavolaMellett)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfDiavolaMellett))))
                    .addGroup(pnlPizzainkLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(12, 12, 12)
                        .addComponent(lblSongokuMellett)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfSongukoMellett)))
                .addGap(13, 13, 13))
        );
        pnlPizzainkLayout.setVerticalGroup(
            pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPizzainkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHusimadoMellett)
                    .addComponent(txfHusimadoMellett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbHusimado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSongokuMellett)
                    .addComponent(txfSongukoMellett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(6, 6, 6)
                .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNegysajtosMellett)
                    .addComponent(txfNegysajtosMellett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiavolaMellett)
                    .addComponent(txfDiavolaMellett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlExtrafeltet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Extra feltét választása", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        rdbHagyma.setText("Hagyma - 150 ft");

        rdbPaprika.setText("Paprika - 80 ft");

        rdbJalapeno.setText("Jalapeno - 100 ft");

        rdbSzalami.setText("Szalámi - 90 ft");

        javax.swing.GroupLayout pnlExtrafeltetLayout = new javax.swing.GroupLayout(pnlExtrafeltet);
        pnlExtrafeltet.setLayout(pnlExtrafeltetLayout);
        pnlExtrafeltetLayout.setHorizontalGroup(
            pnlExtrafeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtrafeltetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlExtrafeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbSzalami)
                    .addComponent(rdbHagyma)
                    .addComponent(rdbJalapeno)
                    .addComponent(rdbPaprika))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlExtrafeltetLayout.setVerticalGroup(
            pnlExtrafeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtrafeltetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbJalapeno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbHagyma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbSzalami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbPaprika))
        );

        btnBezaras.setText("Ablak bezárása");
        btnBezaras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBezarasActionPerformed(evt);
            }
        });

        btnLeadas.setText("Rendelés leadása");
        btnLeadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeadasActionPerformed(evt);
            }
        });

        pnlFizetesimod.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fizetési mód", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        buttonGroup1.add(rdbKp);
        rdbKp.setSelected(true);
        rdbKp.setText("Készpénz");

        buttonGroup1.add(rdbUtalas);
        rdbUtalas.setText("Utalás");

        buttonGroup1.add(rdbBkFiz);
        rdbBkFiz.setText("Bankkártyás fizetés");

        buttonGroup1.add(rdbBkUtanvet);
        rdbBkUtanvet.setText("Bankkártyás utánvét");

        javax.swing.GroupLayout pnlFizetesimodLayout = new javax.swing.GroupLayout(pnlFizetesimod);
        pnlFizetesimod.setLayout(pnlFizetesimodLayout);
        pnlFizetesimodLayout.setHorizontalGroup(
            pnlFizetesimodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFizetesimodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFizetesimodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbKp)
                    .addComponent(rdbUtalas)
                    .addComponent(rdbBkFiz)
                    .addComponent(rdbBkUtanvet))
                .addContainerGap())
        );
        pnlFizetesimodLayout.setVerticalGroup(
            pnlFizetesimodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFizetesimodLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(rdbKp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbBkUtanvet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbBkFiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbUtalas)
                .addGap(12, 12, 12))
        );

        pnlEtlapkepek.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ételeink megtekintése & Árak", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        pnlHusimadoAr.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "1700 ft", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblHusimado.setForeground(new java.awt.Color(51, 51, 255));
        lblHusimado.setText("<html><u>Húsimádó pizza</u>");
        lblHusimado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHusimado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHusimadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHusimadoArLayout = new javax.swing.GroupLayout(pnlHusimadoAr);
        pnlHusimadoAr.setLayout(pnlHusimadoArLayout);
        pnlHusimadoArLayout.setHorizontalGroup(
            pnlHusimadoArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHusimadoArLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHusimado, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHusimadoArLayout.setVerticalGroup(
            pnlHusimadoArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHusimadoArLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHusimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlSonGokuAr.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "1900 ft", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblSongoku.setForeground(new java.awt.Color(51, 51, 255));
        lblSongoku.setText("<html><u>Son-Goku pizza</u>");
        lblSongoku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSongoku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSongokuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSonGokuArLayout = new javax.swing.GroupLayout(pnlSonGokuAr);
        pnlSonGokuAr.setLayout(pnlSonGokuArLayout);
        pnlSonGokuArLayout.setHorizontalGroup(
            pnlSonGokuArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSonGokuArLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSongoku, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSonGokuArLayout.setVerticalGroup(
            pnlSonGokuArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSonGokuArLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSongoku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlNegysajtosAr.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "2000 ft", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblNegysajtos.setForeground(new java.awt.Color(51, 51, 255));
        lblNegysajtos.setText("<html><u>Négysajtos pizza<u/>");
        lblNegysajtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNegysajtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNegysajtosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNegysajtosArLayout = new javax.swing.GroupLayout(pnlNegysajtosAr);
        pnlNegysajtosAr.setLayout(pnlNegysajtosArLayout);
        pnlNegysajtosArLayout.setHorizontalGroup(
            pnlNegysajtosArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegysajtosArLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNegysajtos, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNegysajtosArLayout.setVerticalGroup(
            pnlNegysajtosArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegysajtosArLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNegysajtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlDiavolaAr.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "1900 ft", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblDiavola.setForeground(new java.awt.Color(51, 51, 255));
        lblDiavola.setText("<html><u>Diavola pizza</u>");
        lblDiavola.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDiavola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDiavolaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDiavolaArLayout = new javax.swing.GroupLayout(pnlDiavolaAr);
        pnlDiavolaAr.setLayout(pnlDiavolaArLayout);
        pnlDiavolaArLayout.setHorizontalGroup(
            pnlDiavolaArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiavolaArLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDiavola, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDiavolaArLayout.setVerticalGroup(
            pnlDiavolaArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiavolaArLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDiavola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlEtlapkepekLayout = new javax.swing.GroupLayout(pnlEtlapkepek);
        pnlEtlapkepek.setLayout(pnlEtlapkepekLayout);
        pnlEtlapkepekLayout.setHorizontalGroup(
            pnlEtlapkepekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEtlapkepekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHusimadoAr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(pnlSonGokuAr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(79, 79, 79)
                .addComponent(pnlNegysajtosAr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(pnlDiavolaAr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEtlapkepekLayout.setVerticalGroup(
            pnlEtlapkepekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEtlapkepekLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(pnlEtlapkepekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSonGokuAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlHusimadoAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEtlapkepekLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlEtlapkepekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDiavolaAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlNegysajtosAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pnlAtveletimod.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Átvételi mód", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        cbxAtveteliMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nincs megadva", "Házhozszállítás", "Átvétel éttermünkben" }));

        javax.swing.GroupLayout pnlAtveletimodLayout = new javax.swing.GroupLayout(pnlAtveletimod);
        pnlAtveletimod.setLayout(pnlAtveletimodLayout);
        pnlAtveletimodLayout.setHorizontalGroup(
            pnlAtveletimodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtveletimodLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxAtveteliMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        pnlAtveletimodLayout.setVerticalGroup(
            pnlAtveletimodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbxAtveteliMod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlEtlapkepek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFelso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pnlPizzaink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlExtrafeltet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(pnlFizetesimod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBezaras, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlAtveletimod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLeadas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFelso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPizzaink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlExtrafeltet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFizetesimod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnlEtlapkepek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBezaras)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLeadas)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlAtveletimod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHusimadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHusimadoMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://admin.kemencespizzeria.hu/media/products/201/201410/large/husimado.png"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(BeadandoPizza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblHusimadoMouseClicked

    private void lblSongokuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSongokuMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://caprigyongyos.hu/wp-content/uploads/2019/09/Songoku_.jpg"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(BeadandoPizza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblSongokuMouseClicked

    private void lblNegysajtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNegysajtosMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://i0.wp.com/sprintpizzeria.hu/storage/2021/05/4-sajtos-2.jpg?fit=1200%2C900&ssl=1"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(BeadandoPizza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblNegysajtosMouseClicked

    private void lblDiavolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDiavolaMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://thomassixt.com/wp-content/uploads/sites/2/2023/06/pizza-diavola-1200x800.jpg"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(BeadandoPizza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblDiavolaMouseClicked

    private void btnLeadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeadasActionPerformed
        //JOptionPane.showMessageDialog(null, "A rendelés sikeresen leadva!");
        boolean vanAtvetelimodValasztva = cbxAtveteliMod.getSelectedIndex() > 0;
        if (vanAtvetelimodValasztva){
            JOptionPane.showMessageDialog(null, "Sikeres megrendelés!");
        }else{
            JOptionPane.showMessageDialog(null,"Hiba! Nincs átvételi mód megadva!");
        }
  
    }//GEN-LAST:event_btnLeadasActionPerformed

    private void btnBezarasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBezarasActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnBezarasActionPerformed

    private void ckbHusimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbHusimadoActionPerformed
        txfHusimadoMellett.setText("1");
    }//GEN-LAST:event_ckbHusimadoActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        txfSongukoMellett.setText("1");
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        txfNegysajtosMellett.setText("1");
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        txfDiavolaMellett.setText("1");
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeadandoPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeadandoPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeadandoPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeadandoPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeadandoPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBezaras;
    private javax.swing.JToggleButton btnLeadas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxAtveteliMod;
    private javax.swing.JCheckBox ckbHusimado;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel lblDiavola;
    private javax.swing.JLabel lblDiavolaMellett;
    private javax.swing.JLabel lblHusimado;
    private javax.swing.JLabel lblHusimadoMellett;
    private javax.swing.JLabel lblMotto;
    private javax.swing.JLabel lblNegysajtos;
    private javax.swing.JLabel lblNegysajtosMellett;
    private javax.swing.JLabel lblPizzaHub;
    private javax.swing.JLabel lblRendeloifelulet;
    private javax.swing.JLabel lblSongoku;
    private javax.swing.JLabel lblSongokuMellett;
    private javax.swing.JPanel pnlAtveletimod;
    private javax.swing.JPanel pnlDiavolaAr;
    private javax.swing.JPanel pnlEtlapkepek;
    private javax.swing.JPanel pnlExtrafeltet;
    private javax.swing.JPanel pnlFelso;
    private javax.swing.JPanel pnlFizetesimod;
    private javax.swing.JPanel pnlHusimadoAr;
    private javax.swing.JPanel pnlNegysajtosAr;
    private javax.swing.JPanel pnlPizzaink;
    private javax.swing.JPanel pnlSonGokuAr;
    private javax.swing.JRadioButton rdbBkFiz;
    private javax.swing.JRadioButton rdbBkUtanvet;
    private javax.swing.JRadioButton rdbHagyma;
    private javax.swing.JRadioButton rdbJalapeno;
    private javax.swing.JRadioButton rdbKp;
    private javax.swing.JRadioButton rdbPaprika;
    private javax.swing.JRadioButton rdbSzalami;
    private javax.swing.JRadioButton rdbUtalas;
    private javax.swing.JTextField txfDiavolaMellett;
    private javax.swing.JTextField txfHusimadoMellett;
    private javax.swing.JTextField txfNegysajtosMellett;
    private javax.swing.JTextField txfSongukoMellett;
    // End of variables declaration//GEN-END:variables
}
