/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package beadandopizza;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RichterBalázsKriszti
 */
public class BeadandoPizza extends javax.swing.JFrame {

    /**
     * Creates new form BeadandoPizza
     */
    public BeadandoPizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlFelso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlPizzaink = new javax.swing.JPanel();
        rdbDiavola = new javax.swing.JRadioButton();
        rdbNegysajtos = new javax.swing.JRadioButton();
        rdbHusimado = new javax.swing.JRadioButton();
        rdbSonGoku = new javax.swing.JRadioButton();
        lblHusimadoMellett = new javax.swing.JLabel();
        lblSongokuMellett = new javax.swing.JLabel();
        lblNegysajtosMellett = new javax.swing.JLabel();
        lblDiavolaMellett = new javax.swing.JLabel();
        txfSongukoMellett = new javax.swing.JTextField();
        txfHusimadoMellett = new javax.swing.JTextField();
        txfNegysajtosMellett = new javax.swing.JTextField();
        txfDiavolaMellett = new javax.swing.JTextField();
        pnlExtrafeltet = new javax.swing.JPanel();
        rdbHagyma = new javax.swing.JRadioButton();
        rdbPaprika = new javax.swing.JRadioButton();
        rdbJalapeno = new javax.swing.JRadioButton();
        rdbSzalami = new javax.swing.JRadioButton();
        btnBezaras = new javax.swing.JToggleButton();
        btnLeadas = new javax.swing.JToggleButton();
        pnlFizetesimod = new javax.swing.JPanel();
        rdbKp = new javax.swing.JRadioButton();
        rdbUtalas = new javax.swing.JRadioButton();
        rdbBkFiz = new javax.swing.JRadioButton();
        rdbBkUtanvet = new javax.swing.JRadioButton();
        pnlEtlapkepek = new javax.swing.JPanel();
        lblHusimado = new javax.swing.JLabel();
        lblNegysajtos = new javax.swing.JLabel();
        lblSongoku = new javax.swing.JLabel();
        lblDiavola = new javax.swing.JLabel();
        pnlAtveletimod = new javax.swing.JPanel();
        cbxAtveteliMod = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlFelso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Egyen egy finom pizzát, jó áron!");

        jLabel2.setText("Rendelői felület");

        jLabel3.setText("Pizza Hub");

        javax.swing.GroupLayout pnlFelsoLayout = new javax.swing.GroupLayout(pnlFelso);
        pnlFelso.setLayout(pnlFelsoLayout);
        pnlFelsoLayout.setHorizontalGroup(
            pnlFelsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFelsoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        pnlFelsoLayout.setVerticalGroup(
            pnlFelsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFelsoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFelsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pnlPizzaink.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hagyományos Pizzáink (32 cm)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        rdbDiavola.setText("Diavola");
        rdbDiavola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDiavolaActionPerformed(evt);
            }
        });

        rdbNegysajtos.setText("Négysajtos");
        rdbNegysajtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNegysajtosActionPerformed(evt);
            }
        });

        rdbHusimado.setText("Húsimádó");
        rdbHusimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbHusimadoActionPerformed(evt);
            }
        });

        rdbSonGoku.setText("Son-Goku");
        rdbSonGoku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSonGokuActionPerformed(evt);
            }
        });

        lblHusimadoMellett.setText("db:");

        lblSongokuMellett.setText("db:");

        lblNegysajtosMellett.setText("db:");

        lblDiavolaMellett.setText("db:");

        txfSongukoMellett.setText("Nem kérek");

        txfHusimadoMellett.setText("Nem kérek");

        txfNegysajtosMellett.setText("Nem kérek");

        txfDiavolaMellett.setText("Nem kérek");

        javax.swing.GroupLayout pnlPizzainkLayout = new javax.swing.GroupLayout(pnlPizzaink);
        pnlPizzaink.setLayout(pnlPizzainkLayout);
        pnlPizzainkLayout.setHorizontalGroup(
            pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPizzainkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPizzainkLayout.createSequentialGroup()
                        .addComponent(rdbHusimado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHusimadoMellett)
                        .addGap(4, 4, 4)
                        .addComponent(txfHusimadoMellett, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addGroup(pnlPizzainkLayout.createSequentialGroup()
                        .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbNegysajtos)
                            .addComponent(rdbDiavola))
                        .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPizzainkLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNegysajtosMellett)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfNegysajtosMellett))
                            .addGroup(pnlPizzainkLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblDiavolaMellett)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfDiavolaMellett))))
                    .addGroup(pnlPizzainkLayout.createSequentialGroup()
                        .addComponent(rdbSonGoku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSongokuMellett)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfSongukoMellett)))
                .addGap(13, 13, 13))
        );
        pnlPizzainkLayout.setVerticalGroup(
            pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPizzainkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbHusimado)
                    .addComponent(lblHusimadoMellett)
                    .addComponent(txfHusimadoMellett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbSonGoku)
                    .addComponent(lblSongokuMellett)
                    .addComponent(txfSongukoMellett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbNegysajtos)
                    .addComponent(lblNegysajtosMellett)
                    .addComponent(txfNegysajtosMellett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPizzainkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbDiavola)
                    .addComponent(lblDiavolaMellett)
                    .addComponent(txfDiavolaMellett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlExtrafeltet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Extra feltét választása", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        rdbHagyma.setText("Hagyma");

        rdbPaprika.setText("Paprika");

        rdbJalapeno.setText("Jalapeno");

        rdbSzalami.setText("Szalámi");

        javax.swing.GroupLayout pnlExtrafeltetLayout = new javax.swing.GroupLayout(pnlExtrafeltet);
        pnlExtrafeltet.setLayout(pnlExtrafeltetLayout);
        pnlExtrafeltetLayout.setHorizontalGroup(
            pnlExtrafeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtrafeltetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlExtrafeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbSzalami)
                    .addComponent(rdbHagyma)
                    .addComponent(rdbJalapeno)
                    .addComponent(rdbPaprika))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pnlExtrafeltetLayout.setVerticalGroup(
            pnlExtrafeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtrafeltetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbJalapeno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbHagyma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbSzalami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbPaprika))
        );

        btnBezaras.setText("Ablak bezárása");
        btnBezaras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBezarasActionPerformed(evt);
            }
        });

        btnLeadas.setText("Rendelés leadása");
        btnLeadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeadasActionPerformed(evt);
            }
        });

        pnlFizetesimod.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fizetési mód", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        buttonGroup1.add(rdbKp);
        rdbKp.setText("Készpénz");

        buttonGroup1.add(rdbUtalas);
        rdbUtalas.setText("Utalás");

        buttonGroup1.add(rdbBkFiz);
        rdbBkFiz.setText("Bankkártyás fizetés");

        buttonGroup1.add(rdbBkUtanvet);
        rdbBkUtanvet.setText("Bankkártyás utánvét");

        javax.swing.GroupLayout pnlFizetesimodLayout = new javax.swing.GroupLayout(pnlFizetesimod);
        pnlFizetesimod.setLayout(pnlFizetesimodLayout);
        pnlFizetesimodLayout.setHorizontalGroup(
            pnlFizetesimodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFizetesimodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFizetesimodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbKp)
                    .addComponent(rdbUtalas)
                    .addComponent(rdbBkFiz)
                    .addComponent(rdbBkUtanvet))
                .addContainerGap())
        );
        pnlFizetesimodLayout.setVerticalGroup(
            pnlFizetesimodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFizetesimodLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(rdbKp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbBkUtanvet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbBkFiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbUtalas)
                .addGap(12, 12, 12))
        );

        pnlEtlapkepek.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ételeink megtekintése", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblHusimado.setText("Húsimádó pizza");
        lblHusimado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHusimadoMouseClicked(evt);
            }
        });

        lblNegysajtos.setText("Négysajtos pizza");
        lblNegysajtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNegysajtosMouseClicked(evt);
            }
        });

        lblSongoku.setText("Son-Goku pizza");
        lblSongoku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSongokuMouseClicked(evt);
            }
        });

        lblDiavola.setText("Diavola pizza");
        lblDiavola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDiavolaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlEtlapkepekLayout = new javax.swing.GroupLayout(pnlEtlapkepek);
        pnlEtlapkepek.setLayout(pnlEtlapkepekLayout);
        pnlEtlapkepekLayout.setHorizontalGroup(
            pnlEtlapkepekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEtlapkepekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHusimado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(lblSongoku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(79, 79, 79)
                .addComponent(lblNegysajtos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(lblDiavola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEtlapkepekLayout.setVerticalGroup(
            pnlEtlapkepekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEtlapkepekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEtlapkepekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEtlapkepekLayout.createSequentialGroup()
                        .addGroup(pnlEtlapkepekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHusimado)
                            .addComponent(lblSongoku))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEtlapkepekLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlEtlapkepekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNegysajtos)
                            .addComponent(lblDiavola))))
                .addContainerGap())
        );

        pnlAtveletimod.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Átvételi mód", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        cbxAtveteliMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nincs megadva", "Házhozszállítás", "Átvétel éttermünkben" }));

        javax.swing.GroupLayout pnlAtveletimodLayout = new javax.swing.GroupLayout(pnlAtveletimod);
        pnlAtveletimod.setLayout(pnlAtveletimodLayout);
        pnlAtveletimodLayout.setHorizontalGroup(
            pnlAtveletimodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtveletimodLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(cbxAtveteliMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAtveletimodLayout.setVerticalGroup(
            pnlAtveletimodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbxAtveteliMod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlEtlapkepek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFelso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pnlPizzaink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlExtrafeltet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlFizetesimod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBezaras)
                        .addGap(18, 18, 18)
                        .addComponent(pnlAtveletimod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLeadas)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFelso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPizzaink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlExtrafeltet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFizetesimod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEtlapkepek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAtveletimod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBezaras, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLeadas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHusimadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHusimadoMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://admin.kemencespizzeria.hu/media/products/201/201410/large/husimado.png"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(BeadandoPizza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblHusimadoMouseClicked

    private void lblSongokuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSongokuMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://caprigyongyos.hu/wp-content/uploads/2019/09/Songoku_.jpg"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(BeadandoPizza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblSongokuMouseClicked

    private void lblNegysajtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNegysajtosMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://i0.wp.com/sprintpizzeria.hu/storage/2021/05/4-sajtos-2.jpg?fit=1200%2C900&ssl=1"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(BeadandoPizza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblNegysajtosMouseClicked

    private void lblDiavolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDiavolaMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://thomassixt.com/wp-content/uploads/sites/2/2023/06/pizza-diavola-1200x800.jpg"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(BeadandoPizza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblDiavolaMouseClicked

    private void btnLeadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeadasActionPerformed
        //JOptionPane.showMessageDialog(null, "A rendelés sikeresen leadva!");
        boolean vanAtvetelimodValasztva = cbxAtveteliMod.getSelectedIndex() > 0;
        if (vanAtvetelimodValasztva){
            JOptionPane.showMessageDialog(null, "Sikeres megrendelés!");
        }else{
            JOptionPane.showMessageDialog(null,"Hiba! Nincs átvételi mód megadva!");
}
    }//GEN-LAST:event_btnLeadasActionPerformed

    private void btnBezarasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBezarasActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnBezarasActionPerformed

    private void rdbHusimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbHusimadoActionPerformed
        txfHusimadoMellett.setText("1");
    }//GEN-LAST:event_rdbHusimadoActionPerformed

    private void rdbSonGokuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSonGokuActionPerformed
        txfSongukoMellett.setText("1");
    }//GEN-LAST:event_rdbSonGokuActionPerformed

    private void rdbNegysajtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNegysajtosActionPerformed
        txfNegysajtosMellett.setText("1");
    }//GEN-LAST:event_rdbNegysajtosActionPerformed

    private void rdbDiavolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDiavolaActionPerformed
        txfDiavolaMellett.setText("1");
    }//GEN-LAST:event_rdbDiavolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeadandoPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeadandoPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeadandoPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeadandoPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeadandoPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBezaras;
    private javax.swing.JToggleButton btnLeadas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxAtveteliMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDiavola;
    private javax.swing.JLabel lblDiavolaMellett;
    private javax.swing.JLabel lblHusimado;
    private javax.swing.JLabel lblHusimadoMellett;
    private javax.swing.JLabel lblNegysajtos;
    private javax.swing.JLabel lblNegysajtosMellett;
    private javax.swing.JLabel lblSongoku;
    private javax.swing.JLabel lblSongokuMellett;
    private javax.swing.JPanel pnlAtveletimod;
    private javax.swing.JPanel pnlEtlapkepek;
    private javax.swing.JPanel pnlExtrafeltet;
    private javax.swing.JPanel pnlFelso;
    private javax.swing.JPanel pnlFizetesimod;
    private javax.swing.JPanel pnlPizzaink;
    private javax.swing.JRadioButton rdbBkFiz;
    private javax.swing.JRadioButton rdbBkUtanvet;
    private javax.swing.JRadioButton rdbDiavola;
    private javax.swing.JRadioButton rdbHagyma;
    private javax.swing.JRadioButton rdbHusimado;
    private javax.swing.JRadioButton rdbJalapeno;
    private javax.swing.JRadioButton rdbKp;
    private javax.swing.JRadioButton rdbNegysajtos;
    private javax.swing.JRadioButton rdbPaprika;
    private javax.swing.JRadioButton rdbSonGoku;
    private javax.swing.JRadioButton rdbSzalami;
    private javax.swing.JRadioButton rdbUtalas;
    private javax.swing.JTextField txfDiavolaMellett;
    private javax.swing.JTextField txfHusimadoMellett;
    private javax.swing.JTextField txfNegysajtosMellett;
    private javax.swing.JTextField txfSongukoMellett;
    // End of variables declaration//GEN-END:variables
}
